import java.io.*;



public class Main {
    public static void main(String[] args) {
        // 1. Validate command-line arguments
        if (args.length < 2) {
            System.err.println("Usage Error!");
            System.err.println("Please provide input and output file paths.");
            System.err.println("Example: java Main input.txt output.xml");
            System.exit(1);
        }

        String inputFilePath = args[0];
        String outputFilePath = args[1];

        // 2. Check if the input file exists
        File inputFile = new File(inputFilePath);
        if (!inputFile.exists()) {
            System.err.println("Error: Cannot find input file -> " + inputFilePath);
            System.exit(1);
        }

        System.out.println("Starting to parse file: " + inputFilePath + " ...");

        // 3. Use try-with-resources for automatic stream management
        try (Reader reader = new FileReader(inputFilePath);
             Writer writer = new FileWriter(outputFilePath)) {

            // Initialize Lexer and Parser
            scanner lexer = new scanner(reader);
            parser p = new parser(lexer);
            
            // Execute parsing
            Object result = p.parse();
            
            // 4. If parsing is successful, generate and write XML
            if (result != null && result instanceof FirewallElement) {
                FirewallElement astRoot = (FirewallElement) result;
                
                // Write XML header
                writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
                // Write the XML body generated by the AST node
                writer.write(astRoot.toXML());
                
                System.out.println("[SUCCESS] Parsing complete. XML saved to: " + outputFilePath);
            } else {
                 System.err.println("[WARNING] Parsing finished, but no valid AST was generated.");
            }

        } catch (Exception e) {
            // Note: Syntax errors are handled and printed internally by CUP.
            // This catches file I/O errors or unexpected runtime exceptions.
            System.err.println("[ERROR] An exception occurred during execution: " + e.getMessage());
        }
    }
}