
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\027\000\002\002\003\000\002\002\004\000\002\012" +
    "\002\000\002\012\004\000\002\011\010\000\002\010\002" +
    "\000\002\010\004\000\002\007\021\000\002\006\002\000" +
    "\002\006\004\000\002\005\004\000\002\014\003\000\002" +
    "\014\002\000\002\004\004\000\002\004\002\000\002\003" +
    "\005\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\002\000\002\013\003\000" +
    "\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\006\002\uffff\007\uffff\001\002\000\006\002" +
    "\001\007\010\001\002\000\004\002\006\001\002\000\004" +
    "\002\000\001\002\000\006\002\ufffe\007\ufffe\001\002\000" +
    "\004\010\011\001\002\000\004\030\012\001\002\000\004" +
    "\004\013\001\002\000\006\005\ufffc\011\ufffc\001\002\000" +
    "\006\005\017\011\016\001\002\000\006\005\ufffb\011\ufffb" +
    "\001\002\000\004\030\020\001\002\000\006\002\ufffd\007" +
    "\ufffd\001\002\000\004\004\021\001\002\000\004\012\022" +
    "\001\002\000\004\013\023\001\002\000\004\014\024\001" +
    "\002\000\004\015\025\001\002\000\004\016\026\001\002" +
    "\000\004\027\027\001\002\000\004\006\030\001\002\000" +
    "\004\017\031\001\002\000\004\020\032\001\002\000\004" +
    "\006\033\001\002\000\012\005\ufff9\010\ufff9\020\ufff9\026" +
    "\ufff9\001\002\000\012\005\035\010\ufff3\020\ufff3\026\ufff3" +
    "\001\002\000\006\005\ufffa\011\ufffa\001\002\000\012\005" +
    "\ufff5\010\044\020\042\026\043\001\002\000\012\005\ufff8" +
    "\010\ufff8\020\ufff8\026\ufff8\001\002\000\012\005\ufff7\010" +
    "\ufff7\020\ufff7\026\ufff7\001\002\000\012\005\ufff4\010\ufff4" +
    "\020\ufff4\026\ufff4\001\002\000\012\005\ufff6\010\ufff6\020" +
    "\ufff6\026\ufff6\001\002\000\006\024\056\025\055\001\002" +
    "\000\010\021\045\022\047\023\046\001\002\000\004\027" +
    "\054\001\002\000\006\031\051\032\050\001\002\000\006" +
    "\031\051\032\050\001\002\000\012\005\uffeb\010\uffeb\020" +
    "\uffeb\026\uffeb\001\002\000\012\005\uffec\010\uffec\020\uffec" +
    "\026\uffec\001\002\000\012\005\ufff2\010\ufff2\020\ufff2\026" +
    "\ufff2\001\002\000\012\005\ufff1\010\ufff1\020\ufff1\026\ufff1" +
    "\001\002\000\012\005\ufff0\010\ufff0\020\ufff0\026\ufff0\001" +
    "\002\000\004\027\060\001\002\000\004\027\057\001\002" +
    "\000\012\005\uffef\010\uffef\020\uffef\026\uffef\001\002\000" +
    "\012\005\uffee\010\uffee\020\uffee\026\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\056\000\006\002\004\012\003\001\001\000\004\011" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\013\001\001\000\004\007\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\006\033\001\001\000\006\004" +
    "\035\005\036\001\001\000\002\001\001\000\006\003\040" +
    "\014\037\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\052\001\001\000" +
    "\004\013\051\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        if (info instanceof Symbol){
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left);
                int column = (((Symbol)info).right+1);
                System.err.println(" (line "+line+", column "+column+"): "+message);
            }
        }
    }
    public void syntax_error(Symbol cur_token) {

    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


    public class Param {
        private String type;
        private String value;

        public Param(String type, String value) {
            this.type = type;
            this.value = value;
        }

        public String getType() { return type; }
        public String getValue() { return value; }
    }


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // prog ::= tables 
            {
              Config RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Table[] ts = (Table[])((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    System.out.println("Parser Success");
    if (ts != null) {  Config config = new Config(ts); RESULT = config; }
    else { System.out.println("No tables defined."); }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Config start_val = (Config)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // tables ::= 
            {
              Table[] RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tables",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // tables ::= tables table 
            {
              Table[] RESULT =null;
		int tsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Table[] ts = (Table[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Table t = (Table)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (ts == null) {
                RESULT = new Table[]{(Table)t};
            } else {
                Table[] combined = new Table[ts.length + 1];
                combined[ts.length] = (Table)t;
                System.arraycopy(ts, 0, combined, 0, ts.length);
                RESULT = combined;
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tables",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // table ::= TABLE ADDRESS_FAMILY NAME LBRACE chains RBRACE 
            {
              Table RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int csleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Chain[] cs = (Chain[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
            RESULT = new Table((String)name, (Chain[])cs);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("table",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // chains ::= 
            {
              Chain[] RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chains",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // chains ::= chains chain 
            {
              Chain[] RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Chain[] cs = (Chain[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Chain c = (Chain)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (cs == null) {
                RESULT = new Chain[]{(Chain)c};
            } else {
                Chain[] combined = new Chain[cs.length + 1];
                combined[cs.length] = (Chain)c;
                System.arraycopy(cs, 0, combined, 0, cs.length);
                RESULT = combined;
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chains",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // chain ::= CHAIN NAME LBRACE TYPE TYPE_VAL HOOK HOOK_VAL PRIORITY NUMBER SEMICOLON POLICY ACTION SEMICOLON rules RBRACE 
            {
              Chain RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-13)).value;
		int type_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int type_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		Object type_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;
		int hook_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int hook_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		Object hook_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int priority_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int priority_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Integer priority_val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int policy_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int policy_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object policy_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int rsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		FirewallElement[] rs = (FirewallElement[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
            if(Validator.isValidPriority(priority_val)) {
                RESULT = new Chain((String)name, (String)type_val, (String)hook_val, priority_val,(String)policy_val, (FirewallElement[])rs);
            } else {
                report_error("Invalid policy: " + String.valueOf(priority_val),parser.cur_token); 
                RESULT = null;
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("chain",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // rules ::= 
            {
              FirewallElement[] RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("rules",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // rules ::= rules rule 
            {
              FirewallElement[] RESULT =null;
		int rsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		FirewallElement[] rs = (FirewallElement[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		FirewallElement r = (FirewallElement)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if (rs == null) {
                RESULT = new FirewallElement[]{(FirewallElement)r};
            } else { 
                FirewallElement[] combined = new FirewallElement[rs.length + 1];
                combined[rs.length] = (FirewallElement)r;
                System.arraycopy(rs, 0, combined, 0, rs.length);
                RESULT = combined;
            }
         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("rules",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // rule ::= matches statements 
            {
              FirewallElement RESULT =null;
		int msleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int msright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Param> ms = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String stmts = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            FirewallElement firewall = new FirewallElement();         
            if (stmts != null)  firewall.setAction((String) stmts);
            for (Param p : ms) {
                String value = p.getValue();
                switch (p.getType()) {
                    case "id":       firewall.setId(value); break;
                    case "saddr":    firewall.setSource(value); break;       
                    case "daddr":    firewall.setDestination(value); break;  
                    case "sport":    firewall.setSourcePort(value); break;
                    case "dport":    firewall.setDestinationPort(value); break;
                    case "protocol": firewall.setProtocol(value); break;
                }
            }
            if (firewall.getSource() == null || firewall.getDestination() == null) {
                report_error("Missing source or destination IP address", parser.cur_token);
                RESULT = null; 
            } else {
                RESULT = firewall;
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("rule",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // statements ::= ACTION 
            {
              String RESULT =null;
		int actleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int actright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object act = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (String)act; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statements",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // statements ::= 
            {
              String RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statements",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // matches ::= matches match 
            {
              ArrayList<Param> RESULT =null;
		int msleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int msright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<Param> ms = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int mright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<Param> m = (ArrayList<Param>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                   ms.addAll(m);
                   RESULT = ms;
               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("matches",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // matches ::= 
            {
              ArrayList<Param> RESULT =null;
		
                   RESULT = new ArrayList<Param>();
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("matches",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // match ::= ADDRESS_FAMILY SADDR ip_address 
            {
              ArrayList<Param> RESULT =null;
		int ipleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ipright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String ip = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                ArrayList<Param> list = new ArrayList<>(1);
                list.add(new Param("saddr", ip));
                RESULT = list; 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // match ::= ADDRESS_FAMILY DADDR ip_address 
            {
              ArrayList<Param> RESULT =null;
		int ipleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ipright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String ip = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                ArrayList<Param> list = new ArrayList<>(1);
                list.add(new Param("daddr", ip));
                RESULT = list; 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // match ::= ADDRESS_FAMILY ID NUMBER 
            {
              ArrayList<Param> RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                ArrayList<Param> list = new ArrayList<>(1);
                list.add(new Param("id", String.valueOf(num)));
                RESULT = list; 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // match ::= PROTOCOL SPORT NUMBER 
            {
              ArrayList<Param> RESULT =null;
		int protocolleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int protocolright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object protocol = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                ArrayList<Param> list = new ArrayList<>(2);
                list.add(new Param("protocol", (String)protocol));   
                list.add(new Param("sport", String.valueOf(num)));
                RESULT = list; 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // match ::= PROTOCOL DPORT NUMBER 
            {
              ArrayList<Param> RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer num = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                ArrayList<Param> list = new ArrayList<>(1);
                list.add(new Param("dport", String.valueOf(num)));
                RESULT = list; 
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // match ::= 
            {
              ArrayList<Param> RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("match",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ip_address ::= IP_CIDR 
            {
              String RESULT =null;
		int cidrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cidrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String cidr = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if(Validator.isValidIpv4CIDR(cidr)) {
               RESULT = cidr;
           } else {
               report_error("Invalid IP address: " + cidr,parser.cur_token);
           }
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ip_address",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ip_address ::= IP_RAW 
            {
              String RESULT =null;
		int raw_ipleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int raw_ipright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String raw_ip = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
            if(Validator.isValidIPv4Addres(raw_ip)) {
               RESULT = raw_ip;
           } else {
               report_error("Invalid IP address: " + raw_ip,parser.cur_token);
               RESULT = null;
           }
          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ip_address",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
